In [ ]:
%pip install Pillow
%pip install --upgrade google-genai fsspec gcsfs google-auth google-api-core
import IPython
IPython.Application.instance().kernel.do_shutdown(True)

In [1]:
import google.auth
_, PROJECT_ID = google.auth.default()

In [2]:
from google.genai import types
from google import genai
import concurrent.futures
from PIL import Image
from collections.abc import Callable

def process_image_embedding_worker(id: str, file_path: str):
    client = genai.Client(vertexai=True, location="global", project=PROJECT_ID)
    try:            
        # 임베딩 API 호출
        result = client.models.embed_content(
            model='gemini-embedding-2',
            contents=[
                types.Part.from_uri(file_uri=file_path),
            ],
            config = types.EmbedContentConfig(
                output_dimensionality=768,
                http_options=types.HttpOptions(
                    retry_options=types.HttpRetryOptions(
                        attempts=100,
                        initial_delay=1.0,
                        max_delay=5.0
                    )
                )
            )
        )        
        return [id, file_path, result.embeddings[0].values]
    except Exception as e:
        print(f"API 호출 또는 처리 중 오류 발생 ({id}): {e}")
        return None

def process_text_content_embedding_worker(id: str, content: str):
    client = genai.Client(vertexai=True, location="global", project=PROJECT_ID)
    try:            
        # 임베딩 API 호출
        result = client.models.embed_content(
            model='gemini-embedding-2',
            contents=[
                types.Part.from_text(text=f"title: none | text: {content}"),
            ],
            config = types.EmbedContentConfig(
                output_dimensionality=768,
                http_options=types.HttpOptions(
                    retry_options=types.HttpRetryOptions(
                        attempts=100,
                        initial_delay=1.0,
                        max_delay=5.0
                    )
                )
            )
        )        
        return [id, content, result.embeddings[0].values]
    except Exception as e:
        print(f"API 호출 또는 처리 중 오류 발생 ({id}): {e}")
        return None

def process_image_thumbnail_worker(id: str, file_path: str):
    output = f"./thumbnails/{id}.webp"
    with Image.open(file_path) as img:
        # RGB 모드로 변환 (PNG나 특정 JPG의 투명도/색상 프로필 오류 방지)
        if img.mode in ("RGBA", "P"):
            img = img.convert("RGB")        
        # 한 변의 최대 해상도를 400px로 제한 (비율 유지)
        img.thumbnail((400, 400))        
        # WebP 포맷으로 저장 (quality는 0~100 사이, 80 정도면 화질 저하 없이 용량이 대폭 줄어듭니다)
        img.save(output, format="WEBP", quality=80)
    return [id, file_path, output]

def process_parallel(tasks: list, processor: Callable[[str], str], max_workers: int = 4):
    """
    여러개의 Task를 ThreadPoolExecutor를 이용해 병렬로 동작합니다.
    """
    results_with_index = []
    
    print(f"총 {len(tasks)}개의 데이터를 {max_workers}개의 스레드로 처리합니다...")
    
    # 스레드 풀을 이용한 병렬 처리
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        # 입력된 Task 리스트의 인덱스를 유지하여 순서 보장
        future_to_index = {
            executor.submit(processor, id, data): idx
            for idx, (id, data) in enumerate(tasks)
        }
        
        # 완료되는 순서대로 결과 수집
        i = 0
        for future in concurrent.futures.as_completed(future_to_index):
            i += 1
            if i % 1000 == 0:
                print(f"{i} 개 처리 완료")
            idx = future_to_index[future]
            try:
                res = future.result()
                if res:
                    results_with_index.append((idx, res))
            except Exception as e:
                print(f"스레드 실행 중 예외 발생 (Index {idx}): {e}")

    # 병렬 처리로 인해 뒤섞인 결과를 원래 입력 순서(index)대로 정렬
    results_with_index.sort(key=lambda x: x[0])
    
    # 최종 결과 데이터만 리스트로 반환
    final_results = [res[1] for res in results_with_index]
    return final_results

# 썸네일 생성시 아래 3개의 셀을 수행합니다.
%mkdir ./thumbnails

import os
import glob
from pathlib import Path
# 폴더가 섞여 있을 경우를 대비해 파일만 필터링
images_list = [(Path(f).stem, f) for f in glob.glob('./abo-images-original/**/*.jpg', recursive=True) if os.path.isfile(f)]
print(f"{len(images_list)}개 이미지에 대한 썸네일을 생성합니다.")
thumbnails = process_parallel(images_list, process_image_thumbnail_worker, 64)

%gcloud storage cp -r ./thumbnails gs://jk-amazon-products-thumbnails

In [3]:
# 이미지 임베딩 생성
from pathlib import Path
# ! 명령어를 통해 gcloud 결과를 file_list 변수에 리스트 형태로 저장
# ** 와일드카드를 사용해 하위 폴더의 모든 파일을 재귀적으로 탐색합니다.
file_list = !gcloud storage ls gs://jk-amazon-products/**

print(f"총 {len(file_list)}개의 파일을 찾았습니다.")
images_list = []

for file in file_list:
    if file.endswith(('.png', '.jpg')):
        # Convert gs:// to public gcs path
        images_list.append((Path(file).stem, "https://storage.googleapis.com/" + file[5:]))
print(f"총 {len(images_list)}개의 이미지 파일을 찾았습니다.")

총 398213개의 파일을 찾았습니다.
총 398212개의 이미지 파일을 찾았습니다.

In [4]:
image_embeddings = process_parallel(images_list, process_image_embedding_worker, 64)

총 398212개의 데이터를 64개의 스레드로 처리합니다...
1000 개 처리 완료
2000 개 처리 완료
3000 개 처리 완료
4000 개 처리 완료
5000 개 처리 완료
6000 개 처리 완료
7000 개 처리 완료
8000 개 처리 완료
9000 개 처리 완료
10000 개 처리 완료
11000 개 처리 완료
12000 개 처리 완료
13000 개 처리 완료
14000 개 처리 완료
15000 개 처리 완료
16000 개 처리 완료
17000 개 처리 완료
18000 개 처리 완료
19000 개 처리 완료
20000 개 처리 완료
21000 개 처리 완료
22000 개 처리 완료
23000 개 처리 완료
24000 개 처리 완료
25000 개 처리 완료
26000 개 처리 완료
27000 개 처리 완료
28000 개 처리 완료
29000 개 처리 완료
30000 개 처리 완료
31000 개 처리 완료
32000 개 처리 완료
33000 개 처리 완료
34000 개 처리 완료
35000 개 처리 완료
36000 개 처리 완료
37000 개 처리 완료
38000 개 처리 완료
39000 개 처리 완료
40000 개 처리 완료
41000 개 처리 완료
42000 개 처리 완료
43000 개 처리 완료
44000 개 처리 완료
45000 개 처리 완료
46000 개 처리 완료
47000 개 처리 완료
48000 개 처리 완료
49000 개 처리 완료
50000 개 처리 완료
51000 개 처리 완료
52000 개 처리 완료
53000 개 처리 완료
54000 개 처리 완료
55000 개 처리 완료
56000 개 처리 완료
57000 개 처리 완료
58000 개 처리 완료
59000 개 처리 완료
60000 개 처리 완료
61000 개 처리 완료
62000 개 처리 완료
63000 개 처리 완료
64000 개 처리 완료
65000 개 처리 완료
66000 개 처리 완료
67000 개 처리 완료
68000 개 처리 완료
69000 개 처리 완료
70000 개 처리 완료
71000 개 처리 완료
72000 개 처리 완료
73000 개 처리 완료
74000 개 처리 완료
75000 개 처리 완료
76000 개 처리 완료
77000 개 처리 완료
78000 개 처리 완료
79000 개 처리 완료
80000 개 처리 완료
81000 개 처리 완료
82000 개 처리 완료
83000 개 처리 완료
84000 개 처리 완료
85000 개 처리 완료
86000 개 처리 완료
87000 개 처리 완료
88000 개 처리 완료
89000 개 처리 완료
90000 개 처리 완료
91000 개 처리 완료
92000 개 처리 완료
93000 개 처리 완료
94000 개 처리 완료
95000 개 처리 완료
96000 개 처리 완료
97000 개 처리 완료
98000 개 처리 완료
99000 개 처리 완료
100000 개 처리 완료
101000 개 처리 완료
102000 개 처리 완료
103000 개 처리 완료
104000 개 처리 완료
105000 개 처리 완료
106000 개 처리 완료
107000 개 처리 완료
108000 개 처리 완료
109000 개 처리 완료
110000 개 처리 완료
111000 개 처리 완료
112000 개 처리 완료
113000 개 처리 완료
114000 개 처리 완료
115000 개 처리 완료
116000 개 처리 완료
117000 개 처리 완료
118000 개 처리 완료
119000 개 처리 완료
120000 개 처리 완료
121000 개 처리 완료
122000 개 처리 완료
123000 개 처리 완료
124000 개 처리 완료
125000 개 처리 완료
126000 개 처리 완료
127000 개 처리 완료
128000 개 처리 완료
129000 개 처리 완료
130000 개 처리 완료
131000 개 처리 완료
132000 개 처리 완료
133000 개 처리 완료
134000 개 처리 완료
135000 개 처리 완료
136000 개 처리 완료
137000 개 처리 완료
138000 개 처리 완료
139000 개 처리 완료
140000 개 처리 완료
141000 개 처리 완료
142000 개 처리 완료
143000 개 처리 완료
144000 개 처리 완료
145000 개 처리 완료
146000 개 처리 완료
147000 개 처리 완료
148000 개 처리 완료
149000 개 처리 완료
150000 개 처리 완료
151000 개 처리 완료
152000 개 처리 완료
153000 개 처리 완료
154000 개 처리 완료
155000 개 처리 완료
156000 개 처리 완료
157000 개 처리 완료
158000 개 처리 완료
159000 개 처리 완료
160000 개 처리 완료
161000 개 처리 완료
162000 개 처리 완료
163000 개 처리 완료
164000 개 처리 완료
165000 개 처리 완료
166000 개 처리 완료
167000 개 처리 완료
168000 개 처리 완료
169000 개 처리 완료
API 호출 또는 처리 중 오류 발생 (6c6c5608): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
170000 개 처리 완료
API 호출 또는 처리 중 오류 발생 (6c79af6d): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (6c916354): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
171000 개 처리 완료
172000 개 처리 완료
173000 개 처리 완료
174000 개 처리 완료
175000 개 처리 완료
176000 개 처리 완료
177000 개 처리 완료
178000 개 처리 완료
179000 개 처리 완료
180000 개 처리 완료
181000 개 처리 완료
182000 개 처리 완료
183000 개 처리 완료
184000 개 처리 완료
185000 개 처리 완료
API 호출 또는 처리 중 오류 발생 (774164bb): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (77489e3f): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (7744c954): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (77510194): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (7749d6d2): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (77355a5a): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (77648d9c): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (776b5b73): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (77714e9b): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (7778d71f): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
186000 개 처리 완료
187000 개 처리 완료
188000 개 처리 완료
189000 개 처리 완료
190000 개 처리 완료
191000 개 처리 완료
192000 개 처리 완료
193000 개 처리 완료
194000 개 처리 완료
195000 개 처리 완료
196000 개 처리 완료
197000 개 처리 완료
198000 개 처리 완료
199000 개 처리 완료
200000 개 처리 완료
201000 개 처리 완료
202000 개 처리 완료
203000 개 처리 완료
204000 개 처리 완료
205000 개 처리 완료
206000 개 처리 완료
207000 개 처리 완료
208000 개 처리 완료
209000 개 처리 완료
210000 개 처리 완료
211000 개 처리 완료
212000 개 처리 완료
213000 개 처리 완료
214000 개 처리 완료
215000 개 처리 완료
216000 개 처리 완료
217000 개 처리 완료
218000 개 처리 완료
219000 개 처리 완료
220000 개 처리 완료
221000 개 처리 완료
222000 개 처리 완료
223000 개 처리 완료
224000 개 처리 완료
225000 개 처리 완료
226000 개 처리 완료
227000 개 처리 완료
228000 개 처리 완료
229000 개 처리 완료
230000 개 처리 완료
231000 개 처리 완료
232000 개 처리 완료
233000 개 처리 완료
234000 개 처리 완료
235000 개 처리 완료
236000 개 처리 완료
237000 개 처리 완료
238000 개 처리 완료
239000 개 처리 완료
240000 개 처리 완료
241000 개 처리 완료
242000 개 처리 완료
243000 개 처리 완료
244000 개 처리 완료
245000 개 처리 완료
246000 개 처리 완료
247000 개 처리 완료
248000 개 처리 완료
249000 개 처리 완료
250000 개 처리 완료
251000 개 처리 완료
252000 개 처리 완료
253000 개 처리 완료
254000 개 처리 완료
255000 개 처리 완료
256000 개 처리 완료
257000 개 처리 완료
258000 개 처리 완료
259000 개 처리 완료
260000 개 처리 완료
261000 개 처리 완료
262000 개 처리 완료
263000 개 처리 완료
API 호출 또는 처리 중 오류 발생 (a84c612e): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
264000 개 처리 완료
265000 개 처리 완료
266000 개 처리 완료
267000 개 처리 완료
268000 개 처리 완료
269000 개 처리 완료
270000 개 처리 완료
271000 개 처리 완료
272000 개 처리 완료
273000 개 처리 완료
274000 개 처리 완료
275000 개 처리 완료
276000 개 처리 완료
277000 개 처리 완료
278000 개 처리 완료
279000 개 처리 완료
280000 개 처리 완료
281000 개 처리 완료
282000 개 처리 완료
283000 개 처리 완료
284000 개 처리 완료
285000 개 처리 완료
286000 개 처리 완료
API 호출 또는 처리 중 오류 발생 (b7b863e1): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (b7b44368): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (b76e2223): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (b7b96341): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (b7bc1a79): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (b7b57d21): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (b7ac1c56): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (b7b9fe66): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
API 호출 또는 처리 중 오류 발생 (b7b063e3): 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Cannot fetch content from the provided URL. Please ensure the URL is valid and accessible by Vertex AI. Vertex AI respects robots.txt rules, so confirm the URL is allowed to be crawled. Status: URL_REJECTED-REJECTED_RPC_APP_ERROR', 'status': 'INVALID_ARGUMENT'}}
287000 개 처리 완료
288000 개 처리 완료
289000 개 처리 완료
290000 개 처리 완료
291000 개 처리 완료
292000 개 처리 완료
293000 개 처리 완료
294000 개 처리 완료
295000 개 처리 완료
296000 개 처리 완료
297000 개 처리 완료
298000 개 처리 완료
299000 개 처리 완료
300000 개 처리 완료
301000 개 처리 완료
302000 개 처리 완료
303000 개 처리 완료
304000 개 처리 완료
305000 개 처리 완료
306000 개 처리 완료
307000 개 처리 완료
308000 개 처리 완료
309000 개 처리 완료
310000 개 처리 완료
311000 개 처리 완료
312000 개 처리 완료
313000 개 처리 완료
314000 개 처리 완료
315000 개 처리 완료
316000 개 처리 완료
317000 개 처리 완료
318000 개 처리 완료
319000 개 처리 완료
320000 개 처리 완료
321000 개 처리 완료
322000 개 처리 완료
323000 개 처리 완료
324000 개 처리 완료
325000 개 처리 완료
326000 개 처리 완료
327000 개 처리 완료
328000 개 처리 완료
329000 개 처리 완료
330000 개 처리 완료
331000 개 처리 완료
332000 개 처리 완료
333000 개 처리 완료
334000 개 처리 완료
335000 개 처리 완료
336000 개 처리 완료
337000 개 처리 완료
338000 개 처리 완료
339000 개 처리 완료
340000 개 처리 완료
341000 개 처리 완료
342000 개 처리 완료
343000 개 처리 완료
344000 개 처리 완료
345000 개 처리 완료
346000 개 처리 완료
347000 개 처리 완료
348000 개 처리 완료
349000 개 처리 완료
350000 개 처리 완료
351000 개 처리 완료
352000 개 처리 완료
353000 개 처리 완료
354000 개 처리 완료
355000 개 처리 완료
356000 개 처리 완료
357000 개 처리 완료
358000 개 처리 완료
359000 개 처리 완료
360000 개 처리 완료
361000 개 처리 완료
362000 개 처리 완료
363000 개 처리 완료
364000 개 처리 완료
365000 개 처리 완료
366000 개 처리 완료
367000 개 처리 완료
368000 개 처리 완료
369000 개 처리 완료
370000 개 처리 완료
371000 개 처리 완료
372000 개 처리 완료
373000 개 처리 완료
374000 개 처리 완료
375000 개 처리 완료
376000 개 처리 완료
377000 개 처리 완료
378000 개 처리 완료
379000 개 처리 완료
380000 개 처리 완료
381000 개 처리 완료
382000 개 처리 완료
383000 개 처리 완료
384000 개 처리 완료
385000 개 처리 완료
386000 개 처리 완료
387000 개 처리 완료
388000 개 처리 완료
389000 개 처리 완료
390000 개 처리 완료
391000 개 처리 완료
392000 개 처리 완료
393000 개 처리 완료
394000 개 처리 완료
395000 개 처리 완료
396000 개 처리 완료
397000 개 처리 완료
398000 개 처리 완료

In [18]:
import pandas as pd
df_image_embeddings = pd.DataFrame([
    {"id": item[0], "vectors": {"image_embedding": item[2]}} 
    for item in image_embeddings
])
df_image_embeddings

              id                                            vectors
0       00000529  {'image_embedding': [-0.03478194, -0.005159070...
1       00003a93  {'image_embedding': [-0.028530316, -0.03578147...
2       000088e1  {'image_embedding': [-0.03092741, 0.0020457155...
3       0000b301  {'image_embedding': [0.009060884, -0.030949578...
4       0000b9b8  {'image_embedding': [-0.044396702, -0.01553370...
...          ...                                                ...
398184  ffff4040  {'image_embedding': [-0.011574976, 0.01045859,...
398185  ffff87d7  {'image_embedding': [-0.047705553, -0.05032951...
398186  ffffc378  {'image_embedding': [0.011752412, -0.017997367...
398187  ffffd5c6  {'image_embedding': [-0.030390358, 0.003537298...
398188  ffffe50e  {'image_embedding': [-0.002638914, 0.023899835...

[398189 rows x 2 columns]

In [7]:
# 전체 메타데이터 획득
all_df = []
for i in range(16):
    df = pd.read_json(f'./abo-listings/listings/metadata/listings_{i}.json', lines=True)
    df = df[['main_image_id', 'product_type', 'other_image_id', 'item_name', 'item_keywords', 'country']]
    # 1. other_image_id의 결측치(NaN)를 빈 리스트([])로 변환
    # (리스트끼리 더하기 위해 전처리가 필요합니다)
    safe_other_ids = df['other_image_id'].apply(lambda x: x if isinstance(x, list) else [])
    
    # 2. main_image_id를 리스트로 감싸고, safe_other_ids와 더해서 하나의 큰 리스트로 만듭니다.
    # 예: ['81iZlv3bjpL'] + ['91mIRxgziUL', '91eqBkW06wL'] -> ['81iZlv3bjpL', '91mIRxgziUL', '91eqBkW06wL']
    df['combined_ids'] = df['main_image_id'].apply(lambda x: [x]) + safe_other_ids
    
    # 3. 합쳐진 리스트 컬럼을 기준으로 행을 확장(explode)합니다.
    df = df.explode('combined_ids')
    
    # 4. 확장된 값들을 main_image_id 컬럼에 덮어쓰고, 불필요해진 컬럼들을 삭제합니다.
    df['main_image_id'] = df['combined_ids']
    
    # 5. item_name: 첫 번째 딕셔너리에서 'value' 값만 가져오기 (비어있으면 빈 문자열)
    df['item_name'] = df['item_name'].apply(
        lambda x: x[0].get('value', '') if isinstance(x, list) and x else ''
    )
    
    # 6. item_keywords: 배열 내 딕셔너리를 돌면서 # 붙이고 공백 없앤 뒤 쉼표로 연결
    df['item_keywords'] = df['item_keywords'].apply(
        lambda x: " ".join([f"#{i.get('value', '')}" for i in x]) if isinstance(x, list) else ''
    )
    
    # 7. country 컬럼을 '[국가코드] ' 형태로 만들어 item_name 앞에 붙이기
    df['item_name'] = "[" + df['country'] + "] " + df['item_name']

    # 8. [{'value': 'SHOES'}, {'value': 'BOOTS'}] 형태를 ['SHOES', 'BOOTS'] 형태의 깔끔한 리스트로 변환
    df['product_type'] = df['product_type'].apply(
        lambda x: [i.get('value', '') for i in x] if isinstance(x, list) else []
    )
    
    # 9. 리스트의 원소 개수만큼 행(row)을 확장 (explode)
    df = df.explode('product_type', ignore_index=True)
    
    df = df.drop(columns=['other_image_id', 'combined_ids', 'country'])
    
    # 10. 인덱스 재정렬
    df = df.reset_index(drop=True)
    all_df.append(df)
df_meta = pd.concat(all_df, ignore_index=True)
df_meta

,main_image_id,product_type,item_name,item_keywords
0,81iZlv3bjpL,SHOES,[NL] Amazon-merk - vinden. Dames Leder Geslote...,#block heel shoes #loafer shoes #loafers #meta...
1,91mIRxgziUL,SHOES,[NL] Amazon-merk - vinden. Dames Leder Geslote...,#block heel shoes #loafer shoes #loafers #meta...
2,91eqBkW06wL,SHOES,[NL] Amazon-merk - vinden. Dames Leder Geslote...,#block heel shoes #loafer shoes #loafers #meta...
3,A1BHZSKNbkL,SHOES,[NL] Amazon-merk - vinden. Dames Leder Geslote...,#block heel shoes #loafer shoes #loafers #meta...
4,619y9YG9cnL,HARDWARE,"[MX] 22"" Bottom Mount Drawer Slides, White Pow...",#22 #Pistola #Montaje bajo #diapositivas #Exte...
...,...,...,...,...
711223,81fnxlzmiYL,SHOES,[CA] Amazon Brand - find. Men’s Espadrilles,
711224,81YNklsz4dL,SHOES,[CA] Amazon Brand - find. Men’s Espadrilles,
711225,A1+VHY23fgL,SHOES,[CA] Amazon Brand - find. Men’s Espadrilles,
711226,913lKMbp7OL,SHOES,[CA] Amazon Brand - find. Men’s Espadrilles,
711227,91Tl-bK1vvL,SHOES,[CA] Amazon Brand - find. Men’s Espadrilles,

In [10]:
df_image_path = pd.read_csv('./abo-images-original/images/metadata/images.csv')[['image_id', 'path']]
df_image_path['path'] = df_image_path['path'].str[3:-4]
df_image_path

           image_id      path
0       010-mllS7JL  14fe8812
1       01dkn0Gyx0L  daab0cad
2       01sUPg0387L  d2daaae9
3       1168jc-5r1L  3a4e88e6
4       11RUV5Fs65L  d91ab9cf
...             ...       ...
398207  B1zv8OpTkBS  6d49d130
398208  B1zwflWhPIS  b163e0ea
398209  C1lf45DhhRS  a116d9d1
398210  C1pEt6jBLiS  9c3e1158
398211  C1sCYAz8NAS  cf112e38

[398212 rows x 2 columns]

In [11]:
df_merged = pd.merge(df_meta, df_image_path, left_on='main_image_id', right_on='image_id', how='left')
df_merged = df_merged[['path', 'product_type', 'item_name', 'item_keywords']]
df_merged

,path,product_type,item_name,item_keywords
0,8ccb5859,SHOES,[NL] Amazon-merk - vinden. Dames Leder Geslote...,#block heel shoes #loafer shoes #loafers #meta...
1,13741743,SHOES,[NL] Amazon-merk - vinden. Dames Leder Geslote...,#block heel shoes #loafer shoes #loafers #meta...
2,3062eff1,SHOES,[NL] Amazon-merk - vinden. Dames Leder Geslote...,#block heel shoes #loafer shoes #loafers #meta...
3,8cf58314,SHOES,[NL] Amazon-merk - vinden. Dames Leder Geslote...,#block heel shoes #loafer shoes #loafers #meta...
4,9f76d27b,HARDWARE,"[MX] 22"" Bottom Mount Drawer Slides, White Pow...",#22 #Pistola #Montaje bajo #diapositivas #Exte...
...,...,...,...,...
711223,02d80612,SHOES,[CA] Amazon Brand - find. Men’s Espadrilles,
711224,8c84db9b,SHOES,[CA] Amazon Brand - find. Men’s Espadrilles,
711225,9abc5388,SHOES,[CA] Amazon Brand - find. Men’s Espadrilles,
711226,0179aca5,SHOES,[CA] Amazon Brand - find. Men’s Espadrilles,
711227,85321b64,SHOES,[CA] Amazon Brand - find. Men’s Espadrilles,

In [12]:
# 교집합 체크
len(set(df_image_embeddings['id'].tolist()) & set(df_merged['path'].tolist()))

398147

In [19]:
df_product = pd.merge(df_image_embeddings, df_merged, left_on='id', right_on='path', how='left').drop_duplicates(subset=['id'])
df_product = df_product[["id", 'vectors', 'product_type', 'item_name', 'item_keywords']]
df_product

,id,vectors,product_type,item_name,item_keywords
0,00000529,"{'image_embedding': [-0.03478194, -0.005159070...",HOME,[DE] UMI Slim Laundry Basket on Wheels Tall Ro...,
2,00003a93,"{'image_embedding': [-0.028530316, -0.03578147...",HOME,[ES] UMI. Essentials - Marco Doble para Sobrem...,#Marcos de Foto de estar dormitorio oficina cu...
3,000088e1,"{'image_embedding': [-0.03092741, 0.0020457155...",LAUNDRY_HAMPER,[ES] Eono Amazon Brand Doble Bolsas Cestos par...,#Gran cesta de lavanderia lavado de ropa plega...
4,0000b301,"{'image_embedding': [0.009060884, -0.030949578...",HOME_FURNITURE_AND_DECOR,[MX] Stone & Beam Alfombra Moderna a Rayas,
6,0000b9b8,"{'image_embedding': [-0.044396702, -0.01553370...",WRENCH,[ES] AmazonBasics - Juego de llaves de trinque...,
...,...,...,...,...,...
710665,ffff4040,"{'image_embedding': [-0.011574976, 0.01045859,...",CHAIR,[CA] AmazonBasics Multi-Purpose Adjustable Off...,#small #makeup #de #big #armless #medical #w/m...
710666,ffff87d7,"{'image_embedding': [-0.047705553, -0.05032951...",HUMIDIFIER,[IN] AmazonBasics Humidifier with Smart Auto-H...,#small #rooms #4010 #homech #humifiers #vicks ...
710667,ffffc378,"{'image_embedding': [0.011752412, -0.017997367...",GROCERY,"[US] 365 Everyday Value, Raspberry Geranium Fr...",#sorbet #dessert #botanical #floral #flowers #...
710668,ffffd5c6,"{'image_embedding': [-0.030390358, 0.003537298...",STORAGE_BAG,[ES] AmazonBasics 3-Bag Laundry Hamper Sorter ...,
710669,ffffe50e,"{'image_embedding': [-0.002638914, 0.023899835...",HANDBAG,[MX] Amazon Brand - The Fix Hampton 2 Crossbod...,#accesorios bolso bolso bolso bolso sacos seño...

In [14]:
# 1. 두 컬럼을 \n\n 구분자로 합쳐 새로운 item_description 컬럼 생성
df_product['item_description'] = df_product['item_name'] + '\n\n' + df_product['item_keywords']

# 2. id와 item_description 컬럼을 튜플 리스트로 변환
tuple_list = list(zip(df_product['id'], df_product['item_description']))
text_embeddings = process_parallel(tuple_list, process_text_content_embedding_worker, 64)

총 398189개의 데이터를 64개의 스레드로 처리합니다...
1000 개 처리 완료
2000 개 처리 완료
3000 개 처리 완료
4000 개 처리 완료
5000 개 처리 완료
6000 개 처리 완료
7000 개 처리 완료
8000 개 처리 완료
9000 개 처리 완료
10000 개 처리 완료
11000 개 처리 완료
12000 개 처리 완료
13000 개 처리 완료
14000 개 처리 완료
15000 개 처리 완료
16000 개 처리 완료
17000 개 처리 완료
18000 개 처리 완료
19000 개 처리 완료
20000 개 처리 완료
21000 개 처리 완료
22000 개 처리 완료
23000 개 처리 완료
24000 개 처리 완료
25000 개 처리 완료
26000 개 처리 완료
27000 개 처리 완료
28000 개 처리 완료
29000 개 처리 완료
30000 개 처리 완료
31000 개 처리 완료
32000 개 처리 완료
33000 개 처리 완료
34000 개 처리 완료
35000 개 처리 완료
36000 개 처리 완료
37000 개 처리 완료
38000 개 처리 완료
39000 개 처리 완료
40000 개 처리 완료
41000 개 처리 완료
42000 개 처리 완료
43000 개 처리 완료
44000 개 처리 완료
45000 개 처리 완료
46000 개 처리 완료
47000 개 처리 완료
48000 개 처리 완료
49000 개 처리 완료
50000 개 처리 완료
51000 개 처리 완료
52000 개 처리 완료
53000 개 처리 완료
54000 개 처리 완료
55000 개 처리 완료
56000 개 처리 완료
57000 개 처리 완료
58000 개 처리 완료
59000 개 처리 완료
60000 개 처리 완료
61000 개 처리 완료
62000 개 처리 완료
63000 개 처리 완료
64000 개 처리 완료
65000 개 처리 완료
66000 개 처리 완료
67000 개 처리 완료
68000 개 처리 완료
69000 개 처리 완료
70000 개 처리 완료
71000 개 처리 완료
72000 개 처리 완료
73000 개 처리 완료
74000 개 처리 완료
75000 개 처리 완료
76000 개 처리 완료
77000 개 처리 완료
78000 개 처리 완료
79000 개 처리 완료
80000 개 처리 완료
81000 개 처리 완료
82000 개 처리 완료
83000 개 처리 완료
84000 개 처리 완료
85000 개 처리 완료
86000 개 처리 완료
87000 개 처리 완료
88000 개 처리 완료
89000 개 처리 완료
90000 개 처리 완료
91000 개 처리 완료
92000 개 처리 완료
93000 개 처리 완료
94000 개 처리 완료
95000 개 처리 완료
96000 개 처리 완료
97000 개 처리 완료
98000 개 처리 완료
99000 개 처리 완료
100000 개 처리 완료
101000 개 처리 완료
102000 개 처리 완료
103000 개 처리 완료
104000 개 처리 완료
105000 개 처리 완료
106000 개 처리 완료
107000 개 처리 완료
108000 개 처리 완료
109000 개 처리 완료
110000 개 처리 완료
111000 개 처리 완료
112000 개 처리 완료
113000 개 처리 완료
114000 개 처리 완료
115000 개 처리 완료
116000 개 처리 완료
117000 개 처리 완료
118000 개 처리 완료
119000 개 처리 완료
120000 개 처리 완료
121000 개 처리 완료
122000 개 처리 완료
123000 개 처리 완료
124000 개 처리 완료
125000 개 처리 완료
126000 개 처리 완료
127000 개 처리 완료
128000 개 처리 완료
129000 개 처리 완료
130000 개 처리 완료
131000 개 처리 완료
132000 개 처리 완료
133000 개 처리 완료
134000 개 처리 완료
135000 개 처리 완료
136000 개 처리 완료
137000 개 처리 완료
138000 개 처리 완료
139000 개 처리 완료
140000 개 처리 완료
141000 개 처리 완료
142000 개 처리 완료
143000 개 처리 완료
144000 개 처리 완료
145000 개 처리 완료
146000 개 처리 완료
147000 개 처리 완료
148000 개 처리 완료
149000 개 처리 완료
150000 개 처리 완료
151000 개 처리 완료
152000 개 처리 완료
153000 개 처리 완료
154000 개 처리 완료
155000 개 처리 완료
156000 개 처리 완료
157000 개 처리 완료
158000 개 처리 완료
159000 개 처리 완료
160000 개 처리 완료
161000 개 처리 완료
162000 개 처리 완료
163000 개 처리 완료
164000 개 처리 완료
165000 개 처리 완료
166000 개 처리 완료
167000 개 처리 완료
168000 개 처리 완료
169000 개 처리 완료
170000 개 처리 완료
171000 개 처리 완료
172000 개 처리 완료
173000 개 처리 완료
174000 개 처리 완료
175000 개 처리 완료
176000 개 처리 완료
177000 개 처리 완료
178000 개 처리 완료
179000 개 처리 완료
180000 개 처리 완료
181000 개 처리 완료
182000 개 처리 완료
183000 개 처리 완료
184000 개 처리 완료
185000 개 처리 완료
186000 개 처리 완료
187000 개 처리 완료
188000 개 처리 완료
189000 개 처리 완료
190000 개 처리 완료
191000 개 처리 완료
192000 개 처리 완료
193000 개 처리 완료
194000 개 처리 완료
195000 개 처리 완료
196000 개 처리 완료
197000 개 처리 완료
198000 개 처리 완료
199000 개 처리 완료
200000 개 처리 완료
201000 개 처리 완료
202000 개 처리 완료
203000 개 처리 완료
204000 개 처리 완료
205000 개 처리 완료
206000 개 처리 완료
207000 개 처리 완료
208000 개 처리 완료
209000 개 처리 완료
210000 개 처리 완료
211000 개 처리 완료
212000 개 처리 완료
213000 개 처리 완료
214000 개 처리 완료
215000 개 처리 완료
216000 개 처리 완료
217000 개 처리 완료
218000 개 처리 완료
219000 개 처리 완료
220000 개 처리 완료
221000 개 처리 완료
222000 개 처리 완료
223000 개 처리 완료
224000 개 처리 완료
225000 개 처리 완료
226000 개 처리 완료
227000 개 처리 완료
228000 개 처리 완료
229000 개 처리 완료
230000 개 처리 완료
231000 개 처리 완료
232000 개 처리 완료
233000 개 처리 완료
234000 개 처리 완료
235000 개 처리 완료
236000 개 처리 완료
237000 개 처리 완료
238000 개 처리 완료
239000 개 처리 완료
240000 개 처리 완료
241000 개 처리 완료
242000 개 처리 완료
243000 개 처리 완료
244000 개 처리 완료
245000 개 처리 완료
246000 개 처리 완료
247000 개 처리 완료
248000 개 처리 완료
249000 개 처리 완료
250000 개 처리 완료
251000 개 처리 완료
252000 개 처리 완료
253000 개 처리 완료
254000 개 처리 완료
255000 개 처리 완료
256000 개 처리 완료
257000 개 처리 완료
258000 개 처리 완료
259000 개 처리 완료
260000 개 처리 완료
261000 개 처리 완료
262000 개 처리 완료
263000 개 처리 완료
264000 개 처리 완료
265000 개 처리 완료
266000 개 처리 완료
267000 개 처리 완료
268000 개 처리 완료
269000 개 처리 완료
270000 개 처리 완료
271000 개 처리 완료
272000 개 처리 완료
273000 개 처리 완료
274000 개 처리 완료
275000 개 처리 완료
276000 개 처리 완료
277000 개 처리 완료
278000 개 처리 완료
279000 개 처리 완료
280000 개 처리 완료
281000 개 처리 완료
282000 개 처리 완료
283000 개 처리 완료
284000 개 처리 완료
285000 개 처리 완료
286000 개 처리 완료
287000 개 처리 완료
288000 개 처리 완료
289000 개 처리 완료
290000 개 처리 완료
291000 개 처리 완료
292000 개 처리 완료
293000 개 처리 완료
294000 개 처리 완료
295000 개 처리 완료
296000 개 처리 완료
297000 개 처리 완료
298000 개 처리 완료
299000 개 처리 완료
300000 개 처리 완료
301000 개 처리 완료
302000 개 처리 완료
303000 개 처리 완료
304000 개 처리 완료
305000 개 처리 완료
306000 개 처리 완료
307000 개 처리 완료
308000 개 처리 완료
309000 개 처리 완료
310000 개 처리 완료
311000 개 처리 완료
312000 개 처리 완료
313000 개 처리 완료
314000 개 처리 완료
315000 개 처리 완료
316000 개 처리 완료
317000 개 처리 완료
318000 개 처리 완료
319000 개 처리 완료
320000 개 처리 완료
321000 개 처리 완료
322000 개 처리 완료
323000 개 처리 완료
324000 개 처리 완료
325000 개 처리 완료
326000 개 처리 완료
327000 개 처리 완료
328000 개 처리 완료
329000 개 처리 완료
330000 개 처리 완료
331000 개 처리 완료
332000 개 처리 완료
333000 개 처리 완료
334000 개 처리 완료
335000 개 처리 완료
336000 개 처리 완료
337000 개 처리 완료
338000 개 처리 완료
339000 개 처리 완료
340000 개 처리 완료
341000 개 처리 완료
342000 개 처리 완료
343000 개 처리 완료
344000 개 처리 완료
345000 개 처리 완료
346000 개 처리 완료
347000 개 처리 완료
348000 개 처리 완료
349000 개 처리 완료
350000 개 처리 완료
351000 개 처리 완료
352000 개 처리 완료
353000 개 처리 완료
354000 개 처리 완료
355000 개 처리 완료
356000 개 처리 완료
357000 개 처리 완료
358000 개 처리 완료
359000 개 처리 완료
360000 개 처리 완료
361000 개 처리 완료
362000 개 처리 완료
363000 개 처리 완료
364000 개 처리 완료
365000 개 처리 완료
366000 개 처리 완료
367000 개 처리 완료
368000 개 처리 완료
369000 개 처리 완료
370000 개 처리 완료
371000 개 처리 완료
372000 개 처리 완료
373000 개 처리 완료
374000 개 처리 완료
375000 개 처리 완료
376000 개 처리 완료
377000 개 처리 완료
378000 개 처리 완료
379000 개 처리 완료
380000 개 처리 완료
381000 개 처리 완료
382000 개 처리 완료
383000 개 처리 완료
384000 개 처리 완료
385000 개 처리 완료
386000 개 처리 완료
387000 개 처리 완료
388000 개 처리 완료
389000 개 처리 완료
390000 개 처리 완료
391000 개 처리 완료
392000 개 처리 완료
393000 개 처리 완료
394000 개 처리 완료
395000 개 처리 완료
396000 개 처리 완료
397000 개 처리 완료
398000 개 처리 완료

In [22]:
df_text_embedding = pd.DataFrame(text_embeddings, columns=['id', 'description', 'text_embedding'])
df_golden_product = pd.merge(df_product, df_text_embedding, on='id', how='left')
# df['vectors']와 df['text_embedding']을 한 행씩 가져와 병합
df_golden_product['vectors'] = [
    {**v, 'text_embedding': t} for v, t in zip(df_golden_product['vectors'], df_golden_product['text_embedding'])
]
df_golden_product['data'] = [
    {'name': n, 'description': d} for n, d in zip(df_golden_product['item_name'], df_golden_product['item_description'])
]
df_golden_product = df_golden_product.drop(["description", "text_embedding"], axis=1)
df_golden_product

,id,vectors,product_type,item_name,item_keywords,item_description,data
0,00000529,"{'image_embedding': [-0.03478194, -0.005159070...",HOME,[DE] UMI Slim Laundry Basket on Wheels Tall Ro...,,[DE] UMI Slim Laundry Basket on Wheels Tall Ro...,{'name': '[DE] UMI Slim Laundry Basket on Whee...
1,00003a93,"{'image_embedding': [-0.028530316, -0.03578147...",HOME,[ES] UMI. Essentials - Marco Doble para Sobrem...,#Marcos de Foto de estar dormitorio oficina cu...,[ES] UMI. Essentials - Marco Doble para Sobrem...,{'name': '[ES] UMI. Essentials - Marco Doble p...
2,000088e1,"{'image_embedding': [-0.03092741, 0.0020457155...",LAUNDRY_HAMPER,[ES] Eono Amazon Brand Doble Bolsas Cestos par...,#Gran cesta de lavanderia lavado de ropa plega...,[ES] Eono Amazon Brand Doble Bolsas Cestos par...,{'name': '[ES] Eono Amazon Brand Doble Bolsas ...
3,0000b301,"{'image_embedding': [0.009060884, -0.030949578...",HOME_FURNITURE_AND_DECOR,[MX] Stone & Beam Alfombra Moderna a Rayas,,[MX] Stone & Beam Alfombra Moderna a Rayas\n\n,{'name': '[MX] Stone & Beam Alfombra Moderna a...
4,0000b9b8,"{'image_embedding': [-0.044396702, -0.01553370...",WRENCH,[ES] AmazonBasics - Juego de llaves de trinque...,,[ES] AmazonBasics - Juego de llaves de trinque...,{'name': '[ES] AmazonBasics - Juego de llaves ...
...,...,...,...,...,...,...,...
398184,ffff4040,"{'image_embedding': [-0.011574976, 0.01045859,...",CHAIR,[CA] AmazonBasics Multi-Purpose Adjustable Off...,#small #makeup #de #big #armless #medical #w/m...,[CA] AmazonBasics Multi-Purpose Adjustable Off...,{'name': '[CA] AmazonBasics Multi-Purpose Adju...
398185,ffff87d7,"{'image_embedding': [-0.047705553, -0.05032951...",HUMIDIFIER,[IN] AmazonBasics Humidifier with Smart Auto-H...,#small #rooms #4010 #homech #humifiers #vicks ...,[IN] AmazonBasics Humidifier with Smart Auto-H...,{'name': '[IN] AmazonBasics Humidifier with Sm...
398186,ffffc378,"{'image_embedding': [0.011752412, -0.017997367...",GROCERY,"[US] 365 Everyday Value, Raspberry Geranium Fr...",#sorbet #dessert #botanical #floral #flowers #...,"[US] 365 Everyday Value, Raspberry Geranium Fr...","{'name': '[US] 365 Everyday Value, Raspberry G..."
398187,ffffd5c6,"{'image_embedding': [-0.030390358, 0.003537298...",STORAGE_BAG,[ES] AmazonBasics 3-Bag Laundry Hamper Sorter ...,,[ES] AmazonBasics 3-Bag Laundry Hamper Sorter ...,{'name': '[ES] AmazonBasics 3-Bag Laundry Hamp...
398188,ffffe50e,"{'image_embedding': [-0.002638914, 0.023899835...",HANDBAG,[MX] Amazon Brand - The Fix Hampton 2 Crossbod...,#accesorios bolso bolso bolso bolso sacos seño...,[MX] Amazon Brand - The Fix Hampton 2 Crossbod...,{'name': '[MX] Amazon Brand - The Fix Hampton ...

In [23]:
df_golden_product.to_parquet("amazon_products_golden.parquet")

In [25]:
!gcloud storage cp amazon_products_golden.parquet gs://jk-amazon-products-index/golden-records/

WARNING: Parallel composite upload was turned ON to get the best performance on
uploading large objects. If you would like to opt-out and instead
perform a normal upload, run:
`gcloud config set storage/parallel_composite_upload_enabled False`
If you would like to disable this warning, run:
`gcloud config set storage/parallel_composite_upload_enabled True`
Note that with parallel composite uploads, your object might be
uploaded as a composite object
(https://cloud.google.com/storage/docs/composite-objects), which means
that any user who downloads your object will need to use crc32c
checksums to verify data integrity. gcloud storage is capable of
computing crc32c checksums, but this might pose a problem for other
clients.

Copying file://amazon_products_golden.parquet to gs://jk-amazon-products-index/golden-records/amazon_products_golden.parquet
  Completed files 32/1 | 4.8GiB/4.8GiB | 1.4GiB/s

Average throughput: 1.2GiB/s